export const rtReactionLibrary = [
  {category:"aromatic", from:"benzene", to:"nitrobenzene", answer:"conc. HNO3 + conc. H2SO4"},
  {category:"aromatic", from:"benzene", to:"bromobenzene", answer:"Br2 / FeBr3"},
  {category:"aromatic", from:"benzene", to:"methylbenzene", answer:"CH3Cl / AlCl3"},
  {category:"aromatic", from:"nitrobenzene", to:"phenylamine", answer:"Sn / conc. HCl (heat) then NaOH"},
  {category:"aromatic", from:"phenylamine", to:"benzenediazonium chloride", answer:"NaNO2 / HCl (0-5°C)"},
  {category:"aromatic", from:"phenylamine", to:"phenol", answer:"NaNO2 / HCl (>10°C)"},
  {category:"aromatic", from:"benzenediazonium chloride", to:"azo dye", answer:"phenol / NaOH"},
  {category:"aromatic", from:"phenol", to:"2,4,6-tribromophenol", answer:"Br2 (aq)"},
  {category:"aromatic", from:"phenol", to:"2-nitrophenol", answer:"dil. HNO3"},
  {category:"aromatic", from:"phenylamine", to:"phenylammonium chloride", answer:"HCl (aq)"},
  {category:"aliphatic", from:"ethane", to:"chloroethane", answer:"Cl2 / UV light"},
  {category:"aliphatic", from:"ethene", to:"ethanol", answer:"steam / H3PO4 catalyst"},
  {category:"aliphatic", from:"propene", to:"propane", answer:"H2 / Ni (heat)"},
  {category:"aliphatic", from:"propene", to:"2-bromopropane", answer:"HBr"},
  {category:"aliphatic", from:"propene", to:"1,2-dibromopropane", answer:"Br2"},
  {category:"aliphatic", from:"propene", to:"propan-2-ol", answer:"steam / H3PO4 catalyst"},
  {category:"aliphatic", from:"propan-2-ol", to:"propene", answer:"conc. H2SO4 (heat)"},
  {category:"aliphatic", from:"propan-1-ol", to:"propanal", answer:"K2Cr2O7 / H2SO4 (distil)"},
  {category:"aliphatic", from:"propan-1-ol", to:"propanoic acid", answer:"K2Cr2O7 / H2SO4 (reflux)"},
  {category:"aliphatic", from:"propan-2-ol", to:"propanone", answer:"K2Cr2O7 / H2SO4 (reflux)"},
  {category:"aliphatic", from:"ethanol", to:"chloroethane", answer:"HCl / ZnCl2"},
  {category:"aliphatic", from:"ethanol", to:"bromoethane", answer:"KBr / H2SO4"},
  {category:"aliphatic", from:"ethanol", to:"iodoethane", answer:"KI / H3PO4"},
  {category:"aliphatic", from:"ethylamine", to:"ethanol", answer:"NaNO2 / HCl"},
  {category:"aliphatic", from:"bromoethane", to:"ethene", answer:"KOH (ethanol, heat)"},
  {category:"aliphatic", from:"bromoethane", to:"ethanol", answer:"NaOH (aq, heat)"},
  {category:"aliphatic", from:"bromoethane", to:"ethylamine", answer:"excess NH3 (ethanol, heat)"},
  {category:"aliphatic", from:"bromoethane", to:"propanenitrile", answer:"KCN (ethanol, heat)"},
  {category:"aliphatic", from:"propanenitrile", to:"propanoic acid", answer:"dil. H2SO4 or HCl (reflux)"},
  {category:"aliphatic", from:"propanenitrile", to:"sodium propanoate + ammonia", answer:"NaOH (aq, reflux)"},
  {category:"aliphatic", from:"propanenitrile", to:"propylamine", answer:"LiAlH4 (dry ether)"},
  {category:"aliphatic", from:"ethanal", to:"ethanoic acid", answer:"K2Cr2O7 / H2SO4 (reflux)"},
  {category:"aliphatic", from:"ethanal", to:"ethanol", answer:"NaBH4"},
  {category:"aliphatic", from:"ethanal", to:"2-hydroxypropanenitrile", answer:"KCN / HCN"},
  {category:"aliphatic", from:"propanone", to:"propan-2-ol", answer:"NaBH4"},
  {category:"aliphatic", from:"propanoic acid", to:"propan-1-ol", answer:"LiAlH4 (dry ether)"},
  {category:"aliphatic", from:"propanoic acid", to:"propyl propanoate", answer:"propan-1-ol + conc. H2SO4 (reflux)"},
  {category:"aliphatic", from:"propyl propanoate", to:"propanoic acid + propan-1-ol", answer:"dil. H2SO4 (reflux)"},
  {category:"aliphatic", from:"propyl propanoate", to:"sodium propanoate + propan-1-ol", answer:"NaOH (reflux)"},
  {category:"aliphatic", from:"propanoic acid", to:"propanoyl chloride", answer:"SOCl2"},
  {category:"aliphatic", from:"propanoyl chloride", to:"propyl propanoate", answer:"propan-1-ol"},
  {category:"aliphatic", from:"propanoyl chloride", to:"propanamide", answer:"NH3"},
  {category:"aliphatic", from:"propanoyl chloride", to:"propanoic acid", answer:"H2O"},
  {category:"aliphatic", from:"propanamide", to:"propanoic acid + ammonium", answer:"dil. H2SO4 or HCl (reflux)"},
  {category:"aliphatic", from:"propanamide", to:"sodium propanoate + ammonia", answer:"NaOH (aq, reflux)"},
  {category:"aliphatic", from:"propanamide", to:"propanenitrile", answer:"P4O10 (heat)"},
  {category:"aliphatic", from:"sodium propanoate", to:"ethane", answer:"NaOH + CaO (heat)"},
  {category:"aromatic", from:"methylbenzene", to:"benzoic acid", answer:"alkaline KMnO4 (heat) then acidify"}
];

export const rtMultiStepLibrary = [
  {category:"multi", from:"benzene", to:"phenylamine", answer:"1. benzene → nitrobenzene\n   conc. HNO3 + conc. H2SO4\n2. nitrobenzene → phenylamine\n   Sn / conc. HCl (heat) then NaOH"},
  {category:"multi", from:"benzene", to:"phenol", answer:"1. benzene → nitrobenzene\n   conc. HNO3 + conc. H2SO4\n2. nitrobenzene → phenylamine\n   Sn / conc. HCl (heat) then NaOH\n3. phenylamine → phenol\n   NaNO2 / HCl (>10°C)"},
  {category:"multi", from:"benzene", to:"benzoic acid", answer:"1. benzene → methylbenzene\n   CH3Cl / AlCl3\n2. methylbenzene → benzoic acid\n   alkaline KMnO4 (heat) then acidify"},
  {category:"multi", from:"benzene", to:"benzenediazonium chloride", answer:"1. benzene → nitrobenzene\n   conc. HNO3 + conc. H2SO4\n2. nitrobenzene → phenylamine\n   Sn / conc. HCl (heat) then NaOH\n3. phenylamine → benzenediazonium chloride\n   NaNO2 / HCl (0-5°C)"},
  {category:"multi", from:"bromoethane", to:"propanoic acid", answer:"1. bromoethane → propanenitrile\n   KCN (ethanol, heat)\n2. propanenitrile → propanoic acid\n   dil. H2SO4 or HCl (reflux)"},
  {category:"multi", from:"1-bromopropane", to:"butanoic acid", answer:"1. 1-bromopropane → butanenitrile\n   KCN (ethanol, heat)\n2. butanenitrile → butanoic acid\n   dil. H2SO4 or HCl (reflux)"},
  {category:"multi", from:"propene", to:"propan-1-ol", answer:"1. propene → 1-bromopropane\n   HBr + peroxides\n2. 1-bromopropane → propan-1-ol\n   NaOH (aq, heat)"},
  {category:"multi", from:"propan-1-ol", to:"propylamine", answer:"1. propan-1-ol → 1-bromopropane\n   KBr / H2SO4\n2. 1-bromopropane → propylamine\n   excess NH3 (ethanol, heat)"},
  {category:"multi", from:"ethanol", to:"ethylamine", answer:"1. ethanol → bromoethane\n   KBr / H2SO4\n2. bromoethane → ethylamine\n   excess NH3 (ethanol, heat)"},
  {category:"multi", from:"ethanol", to:"propanoic acid", answer:"1. ethanol → bromoethane\n   KBr / H2SO4\n2. bromoethane → propanenitrile\n   KCN (ethanol, heat)\n3. propanenitrile → propanoic acid\n   dil. H2SO4 or HCl (reflux)"},
  {category:"multi", from:"ethene", to:"ethanoic acid", answer:"1. ethene → ethanol\n   steam / H3PO4 catalyst\n2. ethanol → ethanoic acid\n   K2Cr2O7 / H2SO4 (reflux)"},
  {category:"multi", from:"ethene", to:"bromoethane", answer:"1. ethene → ethanol\n   steam / H3PO4 catalyst\n2. ethanol → bromoethane\n   KBr / H2SO4"},
  {category:"multi", from:"ethene", to:"ethylamine", answer:"1. ethene → ethanol\n   steam / H3PO4 catalyst\n2. ethanol → bromoethane\n   KBr / H2SO4\n3. bromoethane → ethylamine\n   excess NH3 (ethanol, heat)"},
  {category:"multi", from:"nitrobenzene", to:"azo dye", answer:"1. nitrobenzene → phenylamine\n   Sn / conc. HCl (heat) then NaOH\n2. phenylamine → benzenediazonium chloride\n   NaNO2 / HCl (0-5°C)\n3. benzenediazonium chloride → azo dye\n   phenol / NaOH"},
  {category:"multi", from:"methylbenzene", to:"benzene", answer:"1. methylbenzene → benzoic acid\n   alkaline KMnO4 (heat) then acidify\n2. benzoic acid → sodium benzoate\n   NaOH\n3. sodium benzoate → benzene\n   NaOH + CaO (heat)"},
  {category:"multi", from:"benzene", to:"azo dye", answer:"1. benzene → nitrobenzene\n   conc. HNO3 + conc. H2SO4\n2. nitrobenzene → phenylamine\n   Sn / conc. HCl (heat) then NaOH\n3. phenylamine → benzenediazonium chloride\n   NaNO2 / HCl (0-5°C)\n4. benzenediazonium chloride → azo dye\n   phenol / NaOH"},
  {category:"multi", from:"propan-1-ol", to:"butanoic acid", answer:"1. propan-1-ol → 1-bromopropane\n   KBr / H2SO4\n2. 1-bromopropane → butanenitrile\n   KCN (ethanol, heat)\n3. butanenitrile → butanoic acid\n   dil. H2SO4 or HCl (reflux)"}
];

export const rtTestLibrary = [
  {category:"tests", from:"alkene", to:"positive test", answer:"Br₂(aq) — orange colour decolourises\nOR acidified KMnO₄ — purple to colourless"},
  {category:"tests", from:"phenol", to:"positive test", answer:"Br₂(aq) — white precipitate\nOR FeCl₃(aq) — violet/purple colour"},
  {category:"tests", from:"carboxylic acid", to:"positive test", answer:"NaHCO₃(aq) — effervescence of CO₂"},
  {category:"tests", from:"aldehyde", to:"positive test", answer:"Tollens' reagent — silver mirror\nOR Fehling's solution — red precipitate"},
  {category:"tests", from:"carbonyl group (aldehyde/ketone)", to:"positive test", answer:"2,4-DNPH — orange/yellow precipitate"},
  {category:"tests", from:"methyl ketone or CH₃CH(OH)-", to:"positive test", answer:"iodoform test (I₂/NaOH) — yellow ppt of CHI₃"},
  {category:"tests", from:"primary/secondary alcohol", to:"positive test", answer:"acidified K₂Cr₂O₇ — orange to green"},
  {category:"tests", from:"haloalkane", to:"positive test", answer:"warm with NaOH(aq) then add AgNO₃(aq) — white/cream/yellow ppt"},
  {category:"tests", from:"ester", to:"positive test", answer:"NaOH(aq) reflux then acidify — carboxylic acid smell or NaHCO₃ test"},
  {category:"tests", from:"amine (aliphatic primary)", to:"positive test", answer:"NaNO₂/HCl → N₂ gas (effervescence) + alcohol"}
];

export const sdReactionLibrary = [
  {category:"aliphatic",type:"alkane_halogenation",reactant:"methane",product:"chloromethane",reagents:"Cl₂ / UV light",smiles:["ccl","clc"]},
  {category:"aliphatic",type:"alkane_halogenation",reactant:"ethane",product:"chloroethane",reagents:"Cl₂ / UV light",smiles:["cccl","clcc"]},
  {category:"aliphatic",type:"alkane_halogenation",reactant:"propane",product:"1-chloropropane",reagents:"Cl₂ / UV light",smiles:["ccccl","clccc"]},
  {category:"aliphatic",type:"alkane_halogenation",reactant:"propane",product:"2-chloropropane",reagents:"Cl₂ / UV light",smiles:["cc(cl)c","clc(c)c"]},
  {category:"aliphatic",type:"alkane_halogenation",reactant:"butane",product:"1-chlorobutane",reagents:"Cl₂ / UV light",smiles:["cccccl","clcccc"]},
  {category:"aliphatic",type:"alkene_hydrogenation",reactant:"ethene",product:"ethane",reagents:"H₂ / Ni (heat)",smiles:["cc"]},
  {category:"aliphatic",type:"alkene_hydrogenation",reactant:"propene",product:"propane",reagents:"H₂ / Ni (heat)",smiles:["ccc"]},
  {category:"aliphatic",type:"alkene_hydrogenation",reactant:"but-1-ene",product:"butane",reagents:"H₂ / Ni (heat)",smiles:["cccc"]},
  {category:"aliphatic",type:"alkene_hydrogenation",reactant:"but-2-ene",product:"butane",reagents:"H₂ / Ni (heat)",smiles:["cccc","c/c=c/c","c/c=c\\c"]},
  {category:"aliphatic",type:"alkene_hydrogenation",reactant:"pent-1-ene",product:"pentane",reagents:"H₂ / Ni (heat)",smiles:["ccccc"]},
  {category:"aliphatic",type:"alkene_addition_hx",reactant:"ethene",product:"bromoethane",reagents:"HBr",smiles:["ccbr","brcc"]},
  {category:"aliphatic",type:"alkene_addition_hx",reactant:"ethene",product:"chloroethane",reagents:"HCl",smiles:["cccl","clcc"]},
  {category:"aliphatic",type:"alkene_addition_hx",reactant:"propene",product:"2-bromopropane",reagents:"HBr",smiles:["cc(br)c","cc(c)br","brc(c)c"]},
  {category:"aliphatic",type:"alkene_addition_hx",reactant:"propene",product:"2-chloropropane",reagents:"HCl",smiles:["cc(cl)c","cc(c)cl","clc(c)c"]},
  {category:"aliphatic",type:"alkene_addition_hx",reactant:"but-1-ene",product:"2-bromobutane",reagents:"HBr",smiles:["ccc(br)c","ccc(c)br","brc(c)cc"]},
  {category:"aliphatic",type:"alkene_addition_x2",reactant:"ethene",product:"1,2-dibromoethane",reagents:"Br₂",smiles:["brccbr","c(br)cbr"]},
  {category:"aliphatic",type:"alkene_addition_x2",reactant:"ethene",product:"1,2-dichloroethane",reagents:"Cl₂",smiles:["clcccl","c(cl)ccl"]},
  {category:"aliphatic",type:"alkene_addition_x2",reactant:"propene",product:"1,2-dibromopropane",reagents:"Br₂",smiles:["brcc(br)c","cc(br)cbr","brc(c)cbr"]},
  {category:"aliphatic",type:"alkene_addition_x2",reactant:"propene",product:"1,2-dichloropropane",reagents:"Cl₂",smiles:["clcc(cl)c","cc(cl)ccl","clc(c)ccl"]},
  {category:"aliphatic",type:"alkene_addition_x2",reactant:"but-1-ene",product:"1,2-dibromobutane",reagents:"Br₂",smiles:["brcc(br)cc","ccc(br)cbr"]},
  {category:"aliphatic",type:"alkene_hydration",reactant:"ethene",product:"ethanol",reagents:"steam / H₃PO₄ catalyst",smiles:["cco","occ"]},
  {category:"aliphatic",type:"alkene_hydration",reactant:"propene",product:"propan-2-ol",reagents:"steam / H₃PO₄ catalyst",smiles:["cc(o)c","cc(c)o","oc(c)c"]},
  {category:"aliphatic",type:"alkene_hydration",reactant:"but-1-ene",product:"butan-2-ol",reagents:"steam / H₃PO₄ catalyst",smiles:["ccc(o)c","ccc(c)o","oc(c)cc"]},
  {category:"aliphatic",type:"alkene_hydration",reactant:"pent-1-ene",product:"pentan-2-ol",reagents:"steam / H₃PO₄ catalyst",smiles:["cccc(o)c","cccc(c)o","oc(c)ccc"]},
  {category:"aliphatic",type:"alcohol_to_halogenoalkane",reactant:"methanol",product:"chloromethane",reagents:"HCl / ZnCl₂",smiles:["ccl","clc"]},
  {category:"aliphatic",type:"alcohol_to_halogenoalkane",reactant:"ethanol",product:"chloroethane",reagents:"HCl / ZnCl₂",smiles:["cccl","clcc"]},
  {category:"aliphatic",type:"alcohol_to_halogenoalkane",reactant:"ethanol",product:"bromoethane",reagents:"KBr / H₂SO₄",smiles:["ccbr","brcc"]},
  {category:"aliphatic",type:"alcohol_to_halogenoalkane",reactant:"ethanol",product:"iodoethane",reagents:"KI / H₃PO₄",smiles:["cci","icc"]},
  {category:"aliphatic",type:"alcohol_to_halogenoalkane",reactant:"propan-1-ol",product:"1-bromopropane",reagents:"KBr / H₂SO₄",smiles:["cccbr","brccc"]},
  {category:"aliphatic",type:"alcohol_to_halogenoalkane",reactant:"propan-1-ol",product:"1-chloropropane",reagents:"HCl / ZnCl₂",smiles:["ccccl","clccc"]},
  {category:"aliphatic",type:"alcohol_to_halogenoalkane",reactant:"butan-1-ol",product:"1-bromobutane",reagents:"KBr / H₂SO₄",smiles:["ccccbr","brcccc"]},
  {category:"aliphatic",type:"primary_alcohol_to_aldehyde",reactant:"methanol",product:"methanal",reagents:"K₂Cr₂O₇ / H₂SO₄ (distil)",smiles:["c=o","cho","o=c"]},
  {category:"aliphatic",type:"primary_alcohol_to_aldehyde",reactant:"ethanol",product:"ethanal",reagents:"K₂Cr₂O₇ / H₂SO₄ (distil)",smiles:["cc=o","ccho","o=cc"]},
  {category:"aliphatic",type:"primary_alcohol_to_aldehyde",reactant:"propan-1-ol",product:"propanal",reagents:"K₂Cr₂O₇ / H₂SO₄ (distil)",smiles:["ccc=o","cccho","o=ccc"]},
  {category:"aliphatic",type:"primary_alcohol_to_aldehyde",reactant:"butan-1-ol",product:"butanal",reagents:"K₂Cr₂O₇ / H₂SO₄ (distil)",smiles:["cccc=o","cccccho","o=cccc"]},
  {category:"aliphatic",type:"primary_alcohol_to_aldehyde",reactant:"pentan-1-ol",product:"pentanal",reagents:"K₂Cr₂O₇ / H₂SO₄ (distil)",smiles:["ccccc=o","ccccccho","o=ccccc"]},
  {category:"aliphatic",type:"primary_alcohol_to_acid",reactant:"methanol",product:"methanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["c(=o)o","c(o)=o","oc=o","o=co"]},
  {category:"aliphatic",type:"primary_alcohol_to_acid",reactant:"ethanol",product:"ethanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c"]},
  {category:"aliphatic",type:"primary_alcohol_to_acid",reactant:"propan-1-ol",product:"propanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc"]},
  {category:"aliphatic",type:"primary_alcohol_to_acid",reactant:"butan-1-ol",product:"butanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc"]},
  {category:"aliphatic",type:"primary_alcohol_to_acid",reactant:"pentan-1-ol",product:"pentanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["ccccc(=o)o","ccccc(o)=o","occccc=o","o=c(o)cccc"]},
  {category:"aliphatic",type:"secondary_alcohol_to_ketone",reactant:"propan-2-ol",product:"propanone",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["cc(=o)c","cc(c)=o","o=c(c)c"]},
  {category:"aliphatic",type:"secondary_alcohol_to_ketone",reactant:"butan-2-ol",product:"butanone",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["ccc(=o)c","ccc(c)=o","o=c(c)cc"]},
  {category:"aliphatic",type:"secondary_alcohol_to_ketone",reactant:"pentan-2-ol",product:"pentan-2-one",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["cccc(=o)c","cccc(c)=o","o=c(c)ccc"]},
  {category:"aliphatic",type:"secondary_alcohol_to_ketone",reactant:"pentan-3-ol",product:"pentan-3-one",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["ccc(=o)cc","ccc(cc)=o","o=c(cc)cc"]},
  {category:"aliphatic",type:"alcohol_dehydration",reactant:"ethanol",product:"ethene",reagents:"conc. H₂SO₄ (heat)",smiles:["c=c"]},
  {category:"aliphatic",type:"alcohol_dehydration",reactant:"propan-1-ol",product:"propene",reagents:"conc. H₂SO₄ (heat)",smiles:["cc=c","c=cc"]},
  {category:"aliphatic",type:"alcohol_dehydration",reactant:"propan-2-ol",product:"propene",reagents:"conc. H₂SO₄ (heat)",smiles:["cc=c","c=cc"]},
  {category:"aliphatic",type:"alcohol_dehydration",reactant:"butan-1-ol",product:"but-1-ene",reagents:"conc. H₂SO₄ (heat)",smiles:["ccc=c","c=ccc"]},
  {category:"aliphatic",type:"alcohol_dehydration",reactant:"butan-2-ol",product:"but-2-ene",reagents:"conc. H₂SO₄ (heat)",smiles:["cc=cc","c=c(c)c","c/c=c/c","c/c=c\\c"]},
  {category:"aliphatic",type:"carbonyl_reduction",reactant:"methanal",product:"methanol",reagents:"NaBH₄",smiles:["co","oc"]},
  {category:"aliphatic",type:"carbonyl_reduction",reactant:"ethanal",product:"ethanol",reagents:"NaBH₄",smiles:["cco","occ"]},
  {category:"aliphatic",type:"carbonyl_reduction",reactant:"propanal",product:"propan-1-ol",reagents:"NaBH₄",smiles:["ccco","occc"]},
  {category:"aliphatic",type:"carbonyl_reduction",reactant:"butanal",product:"butan-1-ol",reagents:"NaBH₄",smiles:["cccco","occcc"]},
  {category:"aliphatic",type:"carbonyl_reduction",reactant:"propanone",product:"propan-2-ol",reagents:"NaBH₄",smiles:["cc(o)c","cc(c)o","oc(c)c"]},
  {category:"aliphatic",type:"carbonyl_reduction",reactant:"butanone",product:"butan-2-ol",reagents:"NaBH₄",smiles:["ccc(o)c","ccc(c)o","oc(c)cc"]},
  {category:"aliphatic",type:"carbonyl_reduction",reactant:"pentan-2-one",product:"pentan-2-ol",reagents:"NaBH₄",smiles:["cccc(o)c","cccc(c)o","oc(c)ccc"]},
  {category:"aliphatic",type:"aldehyde_oxidation",reactant:"methanal",product:"methanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["c(=o)o","c(o)=o","oc=o","o=co"]},
  {category:"aliphatic",type:"aldehyde_oxidation",reactant:"ethanal",product:"ethanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c"]},
  {category:"aliphatic",type:"aldehyde_oxidation",reactant:"propanal",product:"propanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc"]},
  {category:"aliphatic",type:"aldehyde_oxidation",reactant:"butanal",product:"butanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc"]},
  {category:"aliphatic",type:"aldehyde_oxidation",reactant:"pentanal",product:"pentanoic acid",reagents:"K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["ccccc(=o)o","ccccc(o)=o","occccc=o","o=c(o)cccc"]},
  {category:"aliphatic",type:"carbonyl_addition_hcn",reactant:"methanal",product:"hydroxyethanenitrile",reagents:"HCN / NaCN",smiles:["c(o)c#n","n#cc(o)","c(c#n)o","oc(c#n)","cc#n(o)"]},
  {category:"aliphatic",type:"carbonyl_addition_hcn",reactant:"ethanal",product:"2-hydroxypropanenitrile",reagents:"HCN / NaCN",smiles:["cc(o)c#n","n#cc(o)c","cc(c#n)o","cc#nc(o)","oc(c)c#n"]},
  {category:"aliphatic",type:"carbonyl_addition_hcn",reactant:"propanal",product:"2-hydroxybutanenitrile",reagents:"HCN / NaCN",smiles:["ccc(o)c#n","n#cc(o)cc","ccc(c#n)o","ccc#nc(o)","oc(cc)c#n"]},
  {category:"aliphatic",type:"carbonyl_addition_hcn",reactant:"propanone",product:"2-hydroxy-2-methylpropanenitrile",reagents:"HCN / NaCN",smiles:["cc(o)(c)c#n","cc(c)(o)c#n","n#cc(c)(c)o","cc(c)(c#n)o"]},
  {category:"aliphatic",type:"carbonyl_addition_hcn",reactant:"butanone",product:"2-hydroxy-2-methylbutanenitrile",reagents:"HCN / NaCN",smiles:["ccc(o)(c)c#n","ccc(c)(o)c#n","n#cc(c)(cc)o","ccc(c)(c#n)o"]},
  {category:"aliphatic",type:"halogenoalkane_elimination",reactant:"chloroethane",product:"ethene",reagents:"KOH (ethanol, heat)",smiles:["c=c"]},
  {category:"aliphatic",type:"halogenoalkane_elimination",reactant:"bromoethane",product:"ethene",reagents:"KOH (ethanol, heat)",smiles:["c=c"]},
  {category:"aliphatic",type:"halogenoalkane_elimination",reactant:"1-bromopropane",product:"propene",reagents:"KOH (ethanol, heat)",smiles:["cc=c","c=cc"]},
  {category:"aliphatic",type:"halogenoalkane_elimination",reactant:"2-bromopropane",product:"propene",reagents:"KOH (ethanol, heat)",smiles:["cc=c","c=cc"]},
  {category:"aliphatic",type:"halogenoalkane_elimination",reactant:"1-bromobutane",product:"but-1-ene",reagents:"KOH (ethanol, heat)",smiles:["ccc=c","c=ccc"]},
  {category:"aliphatic",type:"halogenoalkane_elimination",reactant:"2-bromobutane",product:"but-2-ene",reagents:"KOH (ethanol, heat)",smiles:["cc=cc","c=c(c)c","c/c=c/c","c/c=c\\c"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_oh",reactant:"chloromethane",product:"methanol",reagents:"NaOH (aq, heat)",smiles:["co","oc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_oh",reactant:"bromoethane",product:"ethanol",reagents:"NaOH (aq, heat)",smiles:["cco","occ"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_oh",reactant:"chloroethane",product:"ethanol",reagents:"NaOH (aq, heat)",smiles:["cco","occ"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_oh",reactant:"1-bromopropane",product:"propan-1-ol",reagents:"NaOH (aq, heat)",smiles:["ccco","occc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_oh",reactant:"2-bromopropane",product:"propan-2-ol",reagents:"NaOH (aq, heat)",smiles:["cc(o)c","cc(c)o","oc(c)c"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_oh",reactant:"1-bromobutane",product:"butan-1-ol",reagents:"NaOH (aq, heat)",smiles:["cccco","occcc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_nh3",reactant:"chloromethane",product:"methylamine",reagents:"excess NH₃ (ethanol, heat)",smiles:["cn","nc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_nh3",reactant:"bromoethane",product:"ethylamine",reagents:"excess NH₃ (ethanol, heat)",smiles:["ccn","ncc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_nh3",reactant:"chloroethane",product:"ethylamine",reagents:"excess NH₃ (ethanol, heat)",smiles:["ccn","ncc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_nh3",reactant:"1-bromopropane",product:"propylamine",reagents:"excess NH₃ (ethanol, heat)",smiles:["cccn","nccc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_nh3",reactant:"2-bromopropane",product:"isopropylamine",reagents:"excess NH₃ (ethanol, heat)",smiles:["cc(n)c","nc(c)c"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_nh3",reactant:"1-bromobutane",product:"butylamine",reagents:"excess NH₃ (ethanol, heat)",smiles:["ccccn","ncccc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_cn",reactant:"chloromethane",product:"ethanenitrile",reagents:"KCN (ethanol, heat)",smiles:["cc#n","n#cc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_cn",reactant:"bromoethane",product:"propanenitrile",reagents:"KCN (ethanol, heat)",smiles:["ccc#n","n#ccc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_cn",reactant:"chloroethane",product:"propanenitrile",reagents:"KCN (ethanol, heat)",smiles:["ccc#n","n#ccc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_cn",reactant:"1-bromopropane",product:"butanenitrile",reagents:"KCN (ethanol, heat)",smiles:["cccc#n","n#cccc"]},
  {category:"aliphatic",type:"halogenoalkane_substitution_cn",reactant:"1-bromobutane",product:"pentanenitrile",reagents:"KCN (ethanol, heat)",smiles:["ccccc#n","n#ccccc"]},
  {category:"aliphatic",type:"nitrile_hydrolysis",reactant:"ethanenitrile",product:"ethanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c"]},
  {category:"aliphatic",type:"nitrile_hydrolysis",reactant:"propanenitrile",product:"propanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc"]},
  {category:"aliphatic",type:"nitrile_hydrolysis",reactant:"butanenitrile",product:"butanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc"]},
  {category:"aliphatic",type:"nitrile_hydrolysis",reactant:"pentanenitrile",product:"pentanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["ccccc(=o)o","ccccc(o)=o","occccc=o","o=c(o)cccc"]},
  {category:"aliphatic",type:"nitrile_reduction",reactant:"ethanenitrile",product:"ethylamine",reagents:"LiAlH₄ (dry ether)",smiles:["ccn","ncc"]},
  {category:"aliphatic",type:"nitrile_reduction",reactant:"propanenitrile",product:"propylamine",reagents:"LiAlH₄ (dry ether)",smiles:["cccn","nccc"]},
  {category:"aliphatic",type:"nitrile_reduction",reactant:"butanenitrile",product:"butylamine",reagents:"LiAlH₄ (dry ether)",smiles:["ccccn","ncccc"]},
  {category:"aliphatic",type:"nitrile_reduction",reactant:"pentanenitrile",product:"pentylamine",reagents:"LiAlH₄ (dry ether)",smiles:["cccccn","nccccc"]},
  {category:"aliphatic",type:"carboxylic_acid_reduction",reactant:"methanoic acid",product:"methanol",reagents:"LiAlH₄ (dry ether)",smiles:["co","oc"]},
  {category:"aliphatic",type:"carboxylic_acid_reduction",reactant:"ethanoic acid",product:"ethanol",reagents:"LiAlH₄ (dry ether)",smiles:["cco","occ"]},
  {category:"aliphatic",type:"carboxylic_acid_reduction",reactant:"propanoic acid",product:"propan-1-ol",reagents:"LiAlH₄ (dry ether)",smiles:["ccco","occc"]},
  {category:"aliphatic",type:"carboxylic_acid_reduction",reactant:"butanoic acid",product:"butan-1-ol",reagents:"LiAlH₄ (dry ether)",smiles:["cccco","occcc"]},
  {category:"aliphatic",type:"acyl_chloride_formation",reactant:"methanoic acid",product:"methanoyl chloride",reagents:"SOCl₂",smiles:["c(=o)cl","c(cl)=o","clc=o","o=ccl","c(cl)=o"]},
  {category:"aliphatic",type:"acyl_chloride_formation",reactant:"ethanoic acid",product:"ethanoyl chloride",reagents:"SOCl₂",smiles:["cc(=o)cl","cc(cl)=o","clcc=o","o=c(cl)c"]},
  {category:"aliphatic",type:"acyl_chloride_formation",reactant:"propanoic acid",product:"propanoyl chloride",reagents:"SOCl₂",smiles:["ccc(=o)cl","ccc(cl)=o","clccc=o","o=c(cl)cc"]},
  {category:"aliphatic",type:"acyl_chloride_formation",reactant:"butanoic acid",product:"butanoyl chloride",reagents:"SOCl₂",smiles:["cccc(=o)cl","cccc(cl)=o","clcccc=o","o=c(cl)ccc"]},
  {category:"aliphatic",type:"acyl_chloride_hydrolysis",reactant:"methanoyl chloride",product:"methanoic acid",reagents:"H₂O",smiles:["c(=o)o","c(o)=o","oc=o","o=co"]},
  {category:"aliphatic",type:"acyl_chloride_hydrolysis",reactant:"ethanoyl chloride",product:"ethanoic acid",reagents:"H₂O",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c"]},
  {category:"aliphatic",type:"acyl_chloride_hydrolysis",reactant:"propanoyl chloride",product:"propanoic acid",reagents:"H₂O",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc"]},
  {category:"aliphatic",type:"acyl_chloride_hydrolysis",reactant:"butanoyl chloride",product:"butanoic acid",reagents:"H₂O",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc"]},
  {category:"aliphatic",type:"acyl_chloride_to_amide",reactant:"methanoyl chloride",product:"methanamide",reagents:"NH₃",smiles:["c(=o)n","nc=o","o=cn","c(n)=o"]},
  {category:"aliphatic",type:"acyl_chloride_to_amide",reactant:"ethanoyl chloride",product:"ethanamide",reagents:"NH₃",smiles:["cc(=o)n","cc(n)=o","ncc=o","o=c(n)c","nc(=o)c"]},
  {category:"aliphatic",type:"acyl_chloride_to_amide",reactant:"propanoyl chloride",product:"propanamide",reagents:"NH₃",smiles:["ccc(=o)n","ccc(n)=o","nccc=o","o=c(n)cc","nc(=o)cc"]},
  {category:"aliphatic",type:"acyl_chloride_to_amide",reactant:"butanoyl chloride",product:"butanamide",reagents:"NH₃",smiles:["cccc(=o)n","cccc(n)=o","ncccc=o","o=c(n)ccc","nc(=o)ccc"]},
  {category:"aliphatic",type:"acyl_chloride_to_ester",reactant:"ethanoyl chloride + methanol",product:"methyl ethanoate",reagents:"room temperature",smiles:["coc(=o)c","cc(=o)oc","o=c(oc)c","coc(c)=o"]},
  {category:"aliphatic",type:"acyl_chloride_to_ester",reactant:"ethanoyl chloride + ethanol",product:"ethyl ethanoate",reagents:"room temperature",smiles:["ccoc(=o)c","cc(=o)occ","o=c(occ)c","ccoc(c)=o"]},
  {category:"aliphatic",type:"acyl_chloride_to_ester",reactant:"propanoyl chloride + methanol",product:"methyl propanoate",reagents:"room temperature",smiles:["coc(=o)cc","ccc(=o)oc","o=c(oc)cc","coc(cc)=o"]},
  {category:"aliphatic",type:"acyl_chloride_to_ester",reactant:"propanoyl chloride + ethanol",product:"ethyl propanoate",reagents:"room temperature",smiles:["ccoc(=o)cc","ccc(=o)occ","o=c(occ)cc","ccoc(cc)=o"]},
  {category:"aliphatic",type:"acyl_chloride_to_ester",reactant:"butanoyl chloride + methanol",product:"methyl butanoate",reagents:"room temperature",smiles:["coc(=o)ccc","cccc(=o)oc","o=c(oc)ccc","coc(ccc)=o"]},
  {category:"aliphatic",type:"esterification",reactant:"methanoic acid + methanol",product:"methyl methanoate",reagents:"conc. H₂SO₄ (heat)",smiles:["coc=o","c(=o)oc","oc(=o)","o=coc"]},
  {category:"aliphatic",type:"esterification",reactant:"ethanoic acid + methanol",product:"methyl ethanoate",reagents:"conc. H₂SO₄ (heat)",smiles:["coc(=o)c","cc(=o)oc","o=c(oc)c","coc(c)=o"]},
  {category:"aliphatic",type:"esterification",reactant:"ethanoic acid + ethanol",product:"ethyl ethanoate",reagents:"conc. H₂SO₄ (heat)",smiles:["ccoc(=o)c","cc(=o)occ","o=c(occ)c","ccoc(c)=o"]},
  {category:"aliphatic",type:"esterification",reactant:"propanoic acid + methanol",product:"methyl propanoate",reagents:"conc. H₂SO₄ (heat)",smiles:["coc(=o)cc","ccc(=o)oc","o=c(oc)cc","coc(cc)=o"]},
  {category:"aliphatic",type:"esterification",reactant:"propanoic acid + ethanol",product:"ethyl propanoate",reagents:"conc. H₂SO₄ (heat)",smiles:["ccoc(=o)cc","ccc(=o)occ","o=c(occ)cc","ccoc(cc)=o"]},
  {category:"aliphatic",type:"esterification",reactant:"butanoic acid + methanol",product:"methyl butanoate",reagents:"conc. H₂SO₄ (heat)",smiles:["coc(=o)ccc","cccc(=o)oc","o=c(oc)ccc","coc(ccc)=o"]},
  {category:"aliphatic",type:"ester_acid_hydrolysis",reactant:"methyl ethanoate",product:"ethanoic acid + methanol",reagents:"dil. H₂SO₄ (reflux)",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c","co","oc"]},
  {category:"aliphatic",type:"ester_acid_hydrolysis",reactant:"ethyl ethanoate",product:"ethanoic acid + ethanol",reagents:"dil. H₂SO₄ (reflux)",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c","cco","occ"]},
  {category:"aliphatic",type:"ester_acid_hydrolysis",reactant:"methyl propanoate",product:"propanoic acid + methanol",reagents:"dil. H₂SO₄ (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc","co","oc"]},
  {category:"aliphatic",type:"ester_acid_hydrolysis",reactant:"ethyl propanoate",product:"propanoic acid + ethanol",reagents:"dil. H₂SO₄ (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc","cco","occ"]},
  {category:"aliphatic",type:"ester_acid_hydrolysis",reactant:"methyl butanoate",product:"butanoic acid + methanol",reagents:"dil. H₂SO₄ (reflux)",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc","co","oc"]},
  {category:"aliphatic",type:"ester_base_hydrolysis",reactant:"methyl ethanoate",product:"sodium ethanoate + methanol",reagents:"NaOH (reflux)",smiles:["cc(=o)[o-]","[o-]c(=o)c","co","oc"]},
  {category:"aliphatic",type:"ester_base_hydrolysis",reactant:"ethyl ethanoate",product:"sodium ethanoate + ethanol",reagents:"NaOH (reflux)",smiles:["cc(=o)[o-]","[o-]c(=o)c","cco","occ"]},
  {category:"aliphatic",type:"ester_base_hydrolysis",reactant:"methyl propanoate",product:"sodium propanoate + methanol",reagents:"NaOH (reflux)",smiles:["ccc(=o)[o-]","[o-]c(=o)cc","co","oc"]},
  {category:"aliphatic",type:"ester_base_hydrolysis",reactant:"ethyl propanoate",product:"sodium propanoate + ethanol",reagents:"NaOH (reflux)",smiles:["ccc(=o)[o-]","[o-]c(=o)cc","cco","occ"]},
  {category:"aliphatic",type:"amide_hydrolysis",reactant:"methanamide",product:"methanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["c(=o)o","c(o)=o","oc=o","o=co"]},
  {category:"aliphatic",type:"amide_hydrolysis",reactant:"ethanamide",product:"ethanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c"]},
  {category:"aliphatic",type:"amide_hydrolysis",reactant:"propanamide",product:"propanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc"]},
  {category:"aliphatic",type:"amide_hydrolysis",reactant:"butanamide",product:"butanoic acid",reagents:"dil. H₂SO₄ or HCl (reflux)",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc"]},
  {category:"aliphatic",type:"amide_dehydration",reactant:"methanamide",product:"methanenitrile",reagents:"P₄O₁₀ (heat)",smiles:["c#n","n#c"]},
  {category:"aliphatic",type:"amide_dehydration",reactant:"ethanamide",product:"ethanenitrile",reagents:"P₄O₁₀ (heat)",smiles:["cc#n","n#cc"]},
  {category:"aliphatic",type:"amide_dehydration",reactant:"propanamide",product:"propanenitrile",reagents:"P₄O₁₀ (heat)",smiles:["ccc#n","n#ccc"]},
  {category:"aliphatic",type:"amide_dehydration",reactant:"butanamide",product:"butanenitrile",reagents:"P₄O₁₀ (heat)",smiles:["cccc#n","n#cccc"]},
  {category:"aliphatic",type:"aliphatic_amine_diazonium",reactant:"methylamine",product:"methanol",reagents:"NaNO₂ / HCl (N₂ gas evolved)",smiles:["co","oc"]},
  {category:"aliphatic",type:"aliphatic_amine_diazonium",reactant:"ethylamine",product:"ethanol",reagents:"NaNO₂ / HCl (N₂ gas evolved)",smiles:["cco","occ"]},
  {category:"aliphatic",type:"aliphatic_amine_diazonium",reactant:"propylamine",product:"propan-1-ol",reagents:"NaNO₂ / HCl (N₂ gas evolved)",smiles:["ccco","occc"]},
  {category:"aliphatic",type:"aliphatic_amine_diazonium",reactant:"butylamine",product:"butan-1-ol",reagents:"NaNO₂ / HCl (N₂ gas evolved)",smiles:["cccco","occcc"]},
  {category:"aromatic",type:"benzene_halogenation",reactant:"benzene",product:"chlorobenzene",reagents:"Cl₂ / FeCl₃",smiles:["clc1ccccc1","c1ccc(cl)cc1"]},
  {category:"aromatic",type:"benzene_halogenation",reactant:"benzene",product:"bromobenzene",reagents:"Br₂ / FeBr₃",smiles:["brc1ccccc1","c1ccc(br)cc1"]},
  {category:"aromatic",type:"benzene_halogenation",reactant:"benzene",product:"iodobenzene",reagents:"I₂ / FeI₃",smiles:["ic1ccccc1","c1ccc(i)cc1"]},
  {category:"aromatic",type:"benzene_nitration",reactant:"benzene",product:"nitrobenzene",reagents:"conc. HNO₃ / conc. H₂SO₄ (50°C)",smiles:["o=n(=o)c1ccccc1","c1ccc(n(=o)=o)cc1"]},
  {category:"aromatic",type:"friedel_crafts_alkylation",reactant:"benzene",product:"methylbenzene",reagents:"CH₃Cl / AlCl₃ (reflux)",smiles:["cc1ccccc1","c1ccc(c)cc1"]},
  {category:"aromatic",type:"friedel_crafts_alkylation",reactant:"benzene",product:"ethylbenzene",reagents:"C₂H₅Cl / AlCl₃ (reflux)",smiles:["ccc1ccccc1","c1ccc(cc)cc1"]},
  {category:"aromatic",type:"friedel_crafts_alkylation",reactant:"benzene",product:"propylbenzene",reagents:"C₃H₇Cl / AlCl₃ (reflux)",smiles:["cccc1ccccc1","c1ccc(ccc)cc1"]},
  {category:"aromatic",type:"friedel_crafts_acylation",reactant:"benzene",product:"phenylethanone",reagents:"CH₃COCl / AlCl₃ (reflux)",smiles:["cc(=o)c1ccccc1","o=c(c)c1ccccc1"]},
  {category:"aromatic",type:"friedel_crafts_acylation",reactant:"benzene",product:"phenylpropanone",reagents:"C₂H₅COCl / AlCl₃ (reflux)",smiles:["ccc(=o)c1ccccc1","o=c(cc)c1ccccc1"]},
  {category:"aromatic",type:"friedel_crafts_acylation",reactant:"benzene",product:"phenylmethanone",reagents:"HCOCl / AlCl₃ (reflux)",smiles:["c(=o)c1ccccc1","o=cc1ccccc1"]},
  {category:"aromatic",type:"nitrobenzene_reduction",reactant:"nitrobenzene",product:"phenylamine",reagents:"Sn / conc. HCl (heat), then NaOH",smiles:["nc1ccccc1","c1ccc(n)cc1"]},
  {category:"aromatic",type:"phenylamine_bromination",reactant:"phenylamine",product:"2,4,6-tribromophenylamine",reagents:"Br₂ (aq)",smiles:["nc1c(br)cc(br)cc1br","brc1cc(br)cc(br)c1n"]},
  {category:"aromatic",type:"phenylamine_diazotisation",reactant:"phenylamine",product:"benzenediazonium chloride",reagents:"NaNO₂ / HCl (<10°C)",smiles:["c1ccc(n#[n+])cc1","n#[n+]c1ccccc1"]},
  {category:"aromatic",type:"phenol_bromination",reactant:"phenol",product:"2,4,6-tribromophenol",reagents:"Br₂ (aq)",smiles:["oc1c(br)cc(br)cc1br","brc1cc(br)cc(br)c1o"]},
  {category:"aromatic",type:"methylbenzene_oxidation",reactant:"methylbenzene",product:"benzoic acid",reagents:"alkaline KMnO₄ (heat), then acidify",smiles:["o=c(o)c1ccccc1","c1ccc(c(=o)o)cc1"]},
  {category:"aromatic",type:"methylbenzene_oxidation",reactant:"ethylbenzene",product:"benzoic acid",reagents:"alkaline KMnO₄ (heat), then acidify",smiles:["o=c(o)c1ccccc1","c1ccc(c(=o)o)cc1"]},
  {category:"aromatic",type:"methylbenzene_oxidation",reactant:"propylbenzene",product:"benzoic acid",reagents:"alkaline KMnO₄ (heat), then acidify",smiles:["o=c(o)c1ccccc1","c1ccc(c(=o)o)cc1"]},
  {category:"aromatic",type:"diazonium_to_phenol",reactant:"benzenediazonium chloride",product:"phenol",reagents:"H₂O (warm, >10°C)",smiles:["oc1ccccc1","c1ccc(o)cc1"]},
  {category:"aromatic",type:"azo_coupling",reactant:"benzenediazonium chloride + phenol",product:"4-hydroxyazobenzene",reagents:"alkaline solution",smiles:["oc1ccc(n=nc2ccccc2)cc1","c1ccc(n=nc2ccc(o)cc2)cc1"]},
  
  // EXPANDED MULTI-STEP SYNTHESIS REACTIONS
  {category:"multi",type:"multi_step",reactant:"benzene",product:"phenylamine",reagents:"1. conc. HNO₃ + conc. H₂SO₄<br>2. Sn / conc. HCl (heat) then NaOH",smiles:["nc1ccccc1","c1ccc(n)cc1"]},
  {category:"multi",type:"multi_step",reactant:"benzene",product:"phenol",reagents:"1. conc. HNO₃ + conc. H₂SO₄<br>2. Sn / conc. HCl (heat) then NaOH<br>3. NaNO₂ / HCl (>10°C)",smiles:["oc1ccccc1","c1ccc(o)cc1"]},
  {category:"multi",type:"multi_step",reactant:"benzene",product:"benzoic acid",reagents:"1. CH₃Cl / AlCl₃<br>2. alkaline KMnO₄ (heat) then acidify",smiles:["o=c(o)c1ccccc1","c1ccc(c(=o)o)cc1"]},
  {category:"multi",type:"multi_step",reactant:"benzene",product:"benzenediazonium chloride",reagents:"1. conc. HNO₃ + conc. H₂SO₄<br>2. Sn / conc. HCl (heat) then NaOH<br>3. NaNO₂ / HCl (0-5°C)",smiles:["c1ccc(n#[n+])cc1","n#[n+]c1ccccc1"]},
  {category:"multi",type:"multi_step",reactant:"bromoethane",product:"propanoic acid",reagents:"1. KCN (ethanol, heat)<br>2. dil. H₂SO₄ or HCl (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc"]},
  {category:"multi",type:"multi_step",reactant:"1-bromopropane",product:"butanoic acid",reagents:"1. KCN (ethanol, heat)<br>2. dil. H₂SO₄ or HCl (reflux)",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc"]},
  {category:"multi",type:"multi_step",reactant:"propene",product:"propan-1-ol",reagents:"1. HBr + peroxides<br>2. NaOH (aq, heat)",smiles:["ccco","occc"]},
  {category:"multi",type:"multi_step",reactant:"propan-1-ol",product:"propylamine",reagents:"1. KBr / H₂SO₄<br>2. excess NH₃ (ethanol, heat)",smiles:["cccn","nccc"]},
  {category:"multi",type:"multi_step",reactant:"ethanol",product:"ethylamine",reagents:"1. KBr / H₂SO₄<br>2. excess NH₃ (ethanol, heat)",smiles:["ccn","ncc"]},
  {category:"multi",type:"multi_step",reactant:"ethanol",product:"propanoic acid",reagents:"1. KBr / H₂SO₄<br>2. KCN (ethanol, heat)<br>3. dil. H₂SO₄ or HCl (reflux)",smiles:["ccc(=o)o","ccc(o)=o","occc=o","o=c(o)cc"]},
  {category:"multi",type:"multi_step",reactant:"ethene",product:"ethanoic acid",reagents:"1. steam / H₃PO₄ catalyst<br>2. K₂Cr₂O₇ / H₂SO₄ (reflux)",smiles:["cc(=o)o","cc(o)=o","occ=o","o=c(o)c"]},
  {category:"multi",type:"multi_step",reactant:"ethene",product:"bromoethane",reagents:"1. steam / H₃PO₄ catalyst<br>2. KBr / H₂SO₄",smiles:["ccbr","brcc"]},
  {category:"multi",type:"multi_step",reactant:"ethene",product:"ethylamine",reagents:"1. steam / H₃PO₄ catalyst<br>2. KBr / H₂SO₄<br>3. excess NH₃ (ethanol, heat)",smiles:["ccn","ncc"]},
  {category:"multi",type:"multi_step",reactant:"nitrobenzene",product:"4-hydroxyazobenzene",reagents:"1. Sn / conc. HCl (heat) then NaOH<br>2. NaNO₂ / HCl (0-5°C)<br>3. phenol / NaOH",smiles:["oc1ccc(n=nc2ccccc2)cc1","c1ccc(n=nc2ccc(o)cc2)cc1"]},
  {category:"multi",type:"multi_step",reactant:"methylbenzene",product:"benzene",reagents:"1. alkaline KMnO₄ (heat) then acidify<br>2. NaOH<br>3. NaOH + CaO (heat)",smiles:["c1ccccc1"]},
  {category:"multi",type:"multi_step",reactant:"benzene",product:"4-hydroxyazobenzene",reagents:"1. conc. HNO₃ + conc. H₂SO₄<br>2. Sn / conc. HCl (heat) then NaOH<br>3. NaNO₂ / HCl (0-5°C)<br>4. phenol / NaOH",smiles:["oc1ccc(n=nc2ccccc2)cc1","c1ccc(n=nc2ccc(o)cc2)cc1"]},
  {category:"multi",type:"multi_step",reactant:"propan-1-ol",product:"butanoic acid",reagents:"1. KBr / H₂SO₄<br>2. KCN (ethanol, heat)<br>3. dil. H₂SO₄ or HCl (reflux)",smiles:["cccc(=o)o","cccc(o)=o","occcc=o","o=c(o)ccc"]}
];

export const itObservationLibrary = [
  // Flame Tests
  {category:"flame", question:"What is the flame test colour for Lithium (Li⁺)?", answer:"Red"},
  {category:"flame", question:"What is the flame test colour for Sodium (Na⁺)?", answer:"Yellow"},
  {category:"flame", question:"What is the flame test colour for Potassium (K⁺)?", answer:"Lilac"},
  {category:"flame", question:"What is the flame test colour for Calcium (Ca²⁺)?", answer:"Brick red"},
  {category:"flame", question:"What is the flame test colour for Barium (Ba²⁺)?", answer:"Apple-green"},
  {category:"flame", question:"What is the flame test colour for Copper(II) (Cu²⁺)?", answer:"Blue-green"},
  {category:"flame", question:"What is the flame test colour for Magnesium (Mg²⁺)?", answer:"No colour"},

  // Aqueous Complex Ions
  {category:"aqueous", question:"What is the colour of aqueous Iron(II) [Fe(H₂O)₆]²⁺?", answer:"Pale green solution"},
  {category:"aqueous", question:"What is the colour of aqueous Iron(III) [Fe(H₂O)₆]³⁺?", answer:"Yellow / Brown solution"},
  {category:"aqueous", question:"What is the colour of aqueous Copper(II) [Cu(H₂O)₆]²⁺?", answer:"Pale blue solution"},
  {category:"aqueous", question:"What is the colour of aqueous Cobalt(II) [Co(H₂O)₆]²⁺?", answer:"Pink solution"},
  {category:"aqueous", question:"What is the colour of aqueous Chromium(III) [Cr(H₂O)₆]³⁺?", answer:"Green (or violet) solution"},
  {category:"aqueous", question:"What is the colour of aqueous Manganese(II) [Mn(H₂O)₆]²⁺?", answer:"Pale pink solution"},

  // Precipitation
  {category:"precipitate", question:"What is observed when a few drops of NaOH(aq) are added to an aqueous Cu²⁺ solution?", answer:"Blue precipitate"},
  {category:"precipitate", question:"What is observed when a few drops of NaOH(aq) are added to an aqueous Fe²⁺ solution?", answer:"Green precipitate (which turns brown on standing in air)"},
  {category:"precipitate", question:"What is observed when a few drops of NaOH(aq) are added to an aqueous Fe³⁺ solution?", answer:"Brown precipitate"},
  {category:"precipitate", question:"What is observed when a few drops of NaOH(aq) are added to an aqueous Cr³⁺ solution?", answer:"Grey-green precipitate"},
  {category:"precipitate", question:"What happens when excess NaOH(aq) is added to the Cr³⁺ precipitate?", answer:"Precipitate dissolves to form a green solution"},
  {category:"precipitate", question:"What is observed when a few drops of NaOH(aq) are added to an aqueous Co²⁺ solution?", answer:"Blue precipitate"},

  // Ligand Exchange
  {category:"ligand", question:"What is observed when excess aqueous ammonia is added dropwise to aqueous Cu²⁺?", answer:"Pale blue precipitate formed initially, which dissolves in excess to form a royal blue solution"},
  {category:"ligand", question:"What is the formula of the complex ion in the royal blue copper-ammonia solution?", answer:"[Cu(NH₃)₄(H₂O)₂]²⁺"},
  {category:"ligand", question:"What is observed when excess concentrated HCl is added to aqueous Cu²⁺?", answer:"Solution turns yellow-green (due to [CuCl₄]²⁻)"},
  {category:"ligand", question:"What is observed when excess concentrated HCl is added to aqueous Co²⁺?", answer:"Solution turns blue (due to [CoCl₄]²⁻)"},
  
  // Rare Aqueous Ions
  {category:"aqueous", question:"What colour is the dichromate(VI) ion (Cr₂O₇²⁻) in aqueous solution?", answer:"Orange"},
  {category:"aqueous", question:"What colour is the chromate(VI) ion (CrO₄²⁻) in aqueous solution?", answer:"Yellow"},
  {category:"aqueous", question:"What colour is the manganate(VII) ion (MnO₄⁻) in aqueous solution?", answer:"Purple"}
];

